version: "3"
services:
  db:
    container_name: 2023-bbe-1-g3-db
    image: 2023-bbe-1-g3-db
    ports:
      - 9049:5432
    restart: always
  backend:
    depends_on:
      - db
    container_name: 2023-bbe-1-g3-backend
    image: 2023-bbe-1-g3-backend
    ports:
      - 30066:33333
    restart: always