version: "3"
services:
  db:
    container_name: 2023-bfs-1-g3-db
    image: 2023-bfs-1-g3-db
    ports:
      - 9053:5432
    restart: always
  backend:
    depends_on:
      - db
    container_name: 2023-bfs-1-g3-backend
    image: 2023-bfs-1-g3-backend
    ports:
      - 30070:33333
    restart: always
  frontend:
    depends_on:
      - db
      - backend
    container_name: 2023-bfs-1-g3-frontend
    image: 2023-bfs-1-g3-frontend
    ports:
      - 4233:80
    restart: always