version: "3"
services:
  db:
    container_name: 2023-bfs-2-g5-db
    image: 2023-bfs-2-g5-db
    ports:
      - 9062:5432
    restart: always
  backend:
    depends_on:
      - db
    container_name: 2023-bfs-2-g5-backend
    image: 2023-bfs-2-g5-backend
    ports:
      - 30079:33333
    restart: always
  frontend:
    depends_on:
      - db
      - backend
    container_name: 2023-bfs-2-g5-frontend
    image: 2023-bfs-2-g5-frontend
    ports:
      - 4242:80
    restart: always