version: "3"
services:
  db:
    container_name: 2023-bfs-1-g1-db
    image: 2023-bfs-1-g1-db
    ports:
      - 9051:5432
    restart: always
  backend:
    depends_on:
      - db
    container_name: 2023-bfs-1-g1-backend
    image: 2023-bfs-1-g1-backend
    ports:
      - 30068:33333
    restart: always
  frontend:
    depends_on:
      - db
      - backend
    container_name: 2023-bfs-1-g1-frontend
    image: 2023-bfs-1-g1-frontend
    ports:
      - 4231:80
    restart: always